### ISSUE TITLE
TypeError:  - Modbus Invalid CRC in response error

### ISSUE THREAD

**Issue by karan369** [GuillermoElectrico/modbus-logger#3]
Hi,

I have one more error, Yesterday that's working fine Data collection and storing exactly as same.

But I got new error Today. I don't know where is the issue. Please see below errors. I tried to reinstall Modbus_tk (version 1.1.0 ) not solved. kindly provide your best solutions.

```
/modbus-logger$ ./read_modbus_device.py --interval 1 --log INFO
Started app
InfluxDB:
Reloading influxDB map as file changed
	 localhost <--> Local InfluxDB
Devices:
Reloading device map as file changed
	 1 <--> Device Group 1
Collected 0 readouts
--- Logging error ---
Traceback (most recent call last):
  File "./read_modbus_device.py", line 109, in collect_and_store
    resultado = masterRTU.execute(device['id'], cst.READ_HOLDING_REGISTERS, parameters[parameter][0], parameters[parameter][1])
  File "/usr/local/lib/python3.6/dist-packages/modbus_tk-1.1.0-py3.6.egg/modbus_tk/utils.py", line 39, in new
    raise excpt
  File "/usr/local/lib/python3.6/dist-packages/modbus_tk-1.1.0-py3.6.egg/modbus_tk/utils.py", line 37, in new
    ret = fcn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/modbus_tk-1.1.0-py3.6.egg/modbus_tk/modbus.py", line 306, in execute
    response_pdu = query.parse_response(response)
  File "/usr/local/lib/python3.6/dist-packages/modbus_tk-1.1.0-py3.6.egg/modbus_tk/modbus_rtu.py", line 60, in parse_response
    raise ModbusInvalidResponseError("Invalid CRC in response")
modbus_tk.exceptions.ModbusInvalidResponseError: Invalid CRC in response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "./read_modbus_device.py", line 305, in <module>
    func=lambda: collector.collect_and_store())
  File "./read_modbus_device.py", line 258, in repeat
    func(*args, **kwargs)
  File "./read_modbus_device.py", line 305, in <lambda>
    func=lambda: collector.collect_and_store())
  File "./read_modbus_device.py", line 143, in collect_and_store
    log.error("Unexpected error:", sys.exc_info()[0])
Message: 'Unexpected error:'
Arguments: (<class 'modbus_tk.exceptions.ModbusInvalidResponseError'>,)
Invalid CRC in response

```

**Comment by GuillermoElectrico** [comment]
That bug is old known, or it's a RS485-USB adapter problem, or it's a wiring problem.

Try uncommenting line 98 ("# time.sleep (0.01) # Sleep for 10 ms between each parameter read to avoid errors") and try 0.5 s (me it has worked well this way)..

**Comment by karan369** [comment]
I tried rewiring and update ' time sleep(0.5s) '

Now its working fine. Thanks for your support.
